### PR TITLE
Use the first 3 sentences from a bio.

### PR DESCRIPTION
**Pull request by dblock**
Alexa talks too much.

### CODE REVIEW

**Comment by ashkan18** [comment]
while you are there can you also add log for https://github.com/artsy/elderfield/issues/34

**Comment by dblock** [comment]
On it @ashkan18.

**Comment by ashkan18** [comment]
Thanks

**Comment by dblock** [comment]
You can merge this if it looks good, don't wait for #34.

**Comment by ashkan18** [comment]
Looks good, I think it would be fun to add option for longer version bio later. Something like either give `more` option at the end of 3 sentences or `Ask Artsy about Andy Warhol long bio` type of thing.

**Comment by dblock** [comment]
Thanks for opening https://github.com/artsy/elderfield/issues/44 @ashkan18

**Pull request merged**
