### PR TITLE
Added test coverage.

### PR DESCRIPTION
**Pull request by dblock**

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Did you forget to update CHANGELOG.md?</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by dblock** [comment]
This currently doesn't work, isn't reporting coverage for anything in subdirectories.

**Comment by dblock** [comment]
This is ready to review @ashkan18.

**Comment by dblock** [comment]
We get a nice report: 

screen shot 2017-01-09 at 12 41 22 pm

**Comment by ashkan18** [comment]
ooh fancy!

**Pull request merged**
